[tool.poetry]
name = "FreeHeatChallenge"
version = "0.1.0"
authors = ["Dmytro Kachurovskyi <mekaa1337@gmail.com>"]
description = "FreeHeat challenge"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.0.1"
pydantic = "^1.10.7"
argparse = "^1.4.0"
matplotlib = "^3.7.1"
